name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flyway CLI
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.7/flyway-commandline-8.5.7-linux-x64.tar.gz | tar xvz
          sudo mv flyway-8.5.7 /usr/local/bin/flyway
          chmod +x /usr/local/bin/flyway

      - name: Configure Flyway
        run: |
          echo "flyway.url=jdbc:snowflake://qs15547.ap-south-1.aws.snowflakecomputing.com" >> flyway.conf
          echo "flyway.user=omkartram" >> flyway.conf
          echo "flyway.password=Omkar123" >> flyway.conf
          echo "flyway.locations=filesystem:sql" >> flyway.conf

      - name: Run Flyway Migrations
        run: |
          flyway -color=always -configFiles=flyway.conf -X migrate
