name: Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download and unzip Flyway
        run: |
          curl -LJO https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.0.0/flyway-commandline-8.0.0-linux-x64.tar.gz
          tar -xzf flyway-commandline-8.0.0-linux-x64.tar.gz

      - name: Set up Snowflake JDBC driver
        run: |
          mkdir -p $HOME/.flyway/drivers
          curl -LJO https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.15.1/snowflake-jdbc-3.15.1.jar
          mv snowflake-jdbc-3.15.1.jar $HOME/.flyway/drivers/

      - name: Run Flyway migrations
        run: |
          ./flyway-8.0.0/flyway -url="jdbc:snowflake://gu65013.europe-west4.gcp.snowflakecomputing.com/?db=prod&schema=public" -user=whyomkar -password=Omkar123 migrate

      - name: Execute Snowflake SQL scripts
        run: |
          snowsql -a your-account -u your-username -p "${{ secrets.SNOWFLAKE_PASSWORD }}" -d your-database -s your-schema -f path/to/sql/scripts
